import type { PlaceSearchSuggestion } from '@/services/placeSearch/types';

export const MOCK_PLACE_SEARCH_RESULTS: PlaceSearchSuggestion[] = [
  {
    source: 'mock',
    googlePlaceId: 'mock-bondi-beach',
    placeName: 'Bondi Beach',
    formattedAddress: 'Sydney NSW, Australia',
    cityName: 'Sydney',
    countryName: 'Australia',
    latitude: -33.8915,
    longitude: 151.2767,
    searchKeywords: ['bondi', 'bondi beach', '본다이', '본다이 비치', '시드니'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-bondi-icebergs-swimming-club',
    placeName: 'Bondi Icebergs Swimming CLUB',
    formattedAddress: 'Bondi Beach NSW, Australia',
    cityName: 'Sydney',
    countryName: 'Australia',
    latitude: -33.8957,
    longitude: 151.2749,
    searchKeywords: ['bondi', 'icebergs', '본다이', '아이스버그', '시드니'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-bondi-pavilion',
    placeName: 'Bondi Pavilion',
    formattedAddress: 'Bondi Beach NSW, Australia',
    cityName: 'Sydney',
    countryName: 'Australia',
    latitude: -33.8907,
    longitude: 151.276,
    searchKeywords: ['bondi', 'pavilion', '본다이', '파빌리온', '시드니'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-sydney-opera-house',
    placeName: 'Sydney Opera House',
    formattedAddress: 'Bennelong Point, Sydney NSW, Australia',
    cityName: 'Sydney',
    countryName: 'Australia',
    latitude: -33.8568,
    longitude: 151.2153,
    searchKeywords: ['sydney', 'opera house', '시드니', '오페라 하우스'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-observatory-hill',
    placeName: 'Observatory Hill',
    formattedAddress: 'Millers Point NSW, Australia',
    cityName: 'Sydney',
    countryName: 'Australia',
    latitude: -33.8596,
    longitude: 151.2048,
    searchKeywords: ['observatory', 'hill', '천문대', '시드니'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-eiffel-tower',
    placeName: 'Eiffel Tower',
    formattedAddress: 'Champ de Mars, Paris, France',
    cityName: 'Paris',
    countryName: 'France',
    latitude: 48.8584,
    longitude: 2.2945,
    searchKeywords: ['eiffel', 'tower', '에펠탑', '파리'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-louvre-museum',
    placeName: 'Louvre Museum',
    formattedAddress: 'Rue de Rivoli, Paris, France',
    cityName: 'Paris',
    countryName: 'France',
    latitude: 48.8606,
    longitude: 2.3376,
    searchKeywords: ['louvre', 'museum', '루브르', '박물관', '파리'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-seine-river',
    placeName: 'Seine River',
    formattedAddress: 'Paris, France',
    cityName: 'Paris',
    countryName: 'France',
    latitude: 48.8566,
    longitude: 2.3522,
    searchKeywords: ['seine', 'river', '세느강', '센강', '파리'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-kiyomizu-dera',
    placeName: 'Kiyomizu-dera',
    formattedAddress: 'Higashiyama Ward, Kyoto, Japan',
    cityName: 'Kyoto',
    countryName: 'Japan',
    latitude: 34.9949,
    longitude: 135.785,
    searchKeywords: ['kiyomizu', 'dera', '청수사', '기요미즈데라', '교토'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-fushimi-inari-taisha',
    placeName: 'Fushimi Inari Taisha',
    formattedAddress: 'Fushimi Ward, Kyoto, Japan',
    cityName: 'Kyoto',
    countryName: 'Japan',
    latitude: 34.9671,
    longitude: 135.7727,
    searchKeywords: ['fushimi', 'inari', '후시미 이나리', '교토'],
  },
  {
    source: 'mock',
    googlePlaceId: 'mock-arashiyama-bamboo-grove',
    placeName: 'Arashiyama Bamboo Grove',
    formattedAddress: 'Ukyo Ward, Kyoto, Japan',
    cityName: 'Kyoto',
    countryName: 'Japan',
    latitude: 35.017,
    longitude: 135.6713,
    searchKeywords: ['arashiyama', 'bamboo', '아라시야마', '대나무숲', '교토'],
  },
];
